.github/workflows/build.yml

attempts to fix 
https://github.com/GeoNet/base-images/actions/runs/5249337497/jobs/9482010122?pr=11#step:3:9

feat: update build to checkout first and push on main

---

config.yaml

be clearer about the image sources

feat: add fqdn to image refs

---

.github/workflows/presubmit-image-exists.yaml

validate whether image for syncing exists

feat: add presubmit image exists

---

config.yaml

something went wrong in the rebase

chore: fix image sync for mkdocs_plus

---

config.yaml

depends on https://github.com/GeoNet/base-images/pull/23

feat: vendor siderolabs/conform image

---

.github/workflows/presubmit-image-documented.yml
README.md

feat: add presubmit image is documented

---

README.md

chore: fix regex for verify-attestion docs

---

README.md
config.yaml

since it is for build and not runtime

chore: update go image name

---

README.md
config.yaml

adding centos7 for legacy apps and stream8 for ci & cd jobs

centos mirroring

---

.github/workflows/presubmit-image-format.yml
README.md
go.mod

checks the image ref format.
ensures only images with tag and digest are synced

feat: add presubmit for image format

---

.github/workflows/build.yml
.github/workflows/presubmit-github-actions-workflow-validator.yml
.github/workflows/scan.yml
.github/workflows/sync.yml

ensure that the workflows are correctly written

feat: add gh action workflow validator

---

config.yaml

fixes this error
https://github.com/GeoNet/base-images/actions/runs/5504241880/jobs/10030259489#step:4:19

chore: update centos:stream8 image

---

README.md
config.yaml

will use this in an updated version of the docs image for it's healthcheck

feat: add curl image to sync

---

config.yaml

feat: add go 1.16

---

.github/workflows/build.yml

Images changes not on main have been pushing. apko has a `--local` flag which is equivalent to a `--push=false` flag.

feat: apko only push on main

---

README.md
config.yaml
images/alpine-xslt/image.yaml

to be used in https://github.com/GeoNet/fdsn/pull/238 for fdsn-quake-consumer's final stage base image

feat: add alpine-xslt

---

.conform.yaml
.github/workflows/policy-conformance.yml

ensure we use convensional commits and such

feat: add conform to the repo

---

README.md
config.yaml
images/alpine-gdal/image.yaml

feat: add alpine-gdal

---

config.yaml

Update core os image

---

README.md
config.yaml
images/alpine-iputils/image.yaml

for use in field-monitoring-project

feat: add alpine-iputils

---

config.yaml

feat: add go1.21

---

.github/workflows/build.yml

feat: restructure build to split Docker and apko

---

.github/workflows/build.yml

fix: remove `cosign download sbom` from docker build

---

config.yaml

chore: update centos image digest

---

config.yaml

update other stream releases
included to support packaging repo work

chore: add stream9

---

.github/workflows/update-image-digests.yml
README.md
config.yaml
hack/update-sync-image-digests.sh

automatically create a PR to update the mutably tagged images

feat: add workflow to update mutably tagged images

---

.github/workflows/update-image-digests.yml

fix: update reference to update sync image digests

---

.github/workflows/update-image-digests.yml

- branch name doesn't come up correctly
- assignee isn't being resolved
https://github.com/GeoNet/base-images/actions/runs/6306877731/job/17122688942#step:8:19
https://github.com/GeoNet/base-images/actions/runs/6306877731/job/17122688942#step:8:29

chore: fix branch name and remove assignee

---

.github/workflows/build.yml

feat: use reusable-docker-build for docker build

---

.github/workflows/build.yml

not building apks into custom base images

chore: remove melange from apko build

---

.github/workflows/build.yml
.github/workflows/scan.yml
.github/workflows/sync.yml

stop unrelated horizontal failure

chore: disable fail-fast for concurrent jobs

---

.github/workflows/build.yml
config.yaml

ensure that longer-to-build images only get built on main

chore: add condition for only building on main

---

.github/workflows/build.yml
.github/workflows/scan.yml
.github/workflows/sync.yml

yq is pre-installed in linux actions runner images

chore: remove yq action

---

images/rpmbuild-centos-stream9/Dockerfile

to allow us to test some builds in the bau processes on rhel9
part of https://github.com/GeoNet/tickets/issues/13505
to fix
https://github.com/GeoNet/packaging/actions/runs/6385583205/job/17331194588

fix: add more dependencies rhel9

---

.github/workflows/update-image-digests.yml

- add label to repo if missing
- add label to image digest update prs

chore: add missing label to image digest update pr

---

.github/workflows/scan.yml

use the reusable workflow for image scanning

chore: use reusable image scan

---

.github/workflows/update-image-digests.yml

ensure other jobs trigger when an image digest update PR comes through

chore: use geonetci user to make updates to images

---

.github/dependabot.yml
config.yaml

use an allowed commit prefix
attempts to resolve: https://github.com/GeoNet/base-images/pull/125
and update base-images
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message

chore: use dependabot semantic commit message

---

.github/dependabot.yml

in case these count as development

chore: add dependabot prefix-development

---

config.yaml

updates sync config.yaml images for 2023-10-31-10-46

Update sync config.yaml images 2023-10-31-10-46

---

.github/workflows/update-image-digests.yml

to pass conform tests
double `-m` fixes it

fix: ensure commit message has a body

---

config.yaml

updates sync config.yaml images for 2023-11-01-09-16

Update sync config.yaml images 2023-11-01-09-16

---

.github/workflows/build.yml
README.md
config.yaml
images/rpmbuild-fedora/Dockerfile

fedora build for pi packaging CI CD

feat: add fedora rpmbuild base

---

config.yaml

updates sync config.yaml images for 2023-11-01-10-00

Update sync config.yaml images 2023-11-01-10-00

---

config.yaml

updates sync config.yaml images for 2023-11-07-14-14

Update sync config.yaml images 2023-11-07-14-14

---

config.yaml

updates sync config.yaml images for 2023-11-09-12-53

Update sync config.yaml images 2023-11-09-12-53

---

config.yaml

updates sync config.yaml images for 2023-11-16-15-08

Update sync config.yaml images 2023-11-16-15-08

---

.github/workflows/build.yml
config.yaml

qemu is too slow to build an image in 30mins on arm64. and breaks trivy scanner

fix: disable arm64 builds

---

config.yaml

updates sync config.yaml images for 2023-11-27-16-01

Update sync config.yaml images 2023-11-27-16-01

---

config.yaml

updates sync config.yaml images for 2023-11-29-16-35

Update sync config.yaml images 2023-11-29-16-35

---

images/rpmbuild-centos7/Dockerfile

consistient with modern releases

fix: provide dnf for rpmbuild

---

config.yaml

updates sync config.yaml images for 2023-12-04-10-51

Update sync config.yaml images 2023-12-04-10-51

---

config.yaml
images/rpmbuild-fedora/Dockerfile.39

f39 is available and can be added to the suite to match coreos going to 39 stable

feat: add fedora 39 to image suite

---

config.yaml

updates sync config.yaml images for 2023-12-19-22-08

Update sync config.yaml images 2023-12-19-22-08

---

config.yaml

updates sync config.yaml images for 2024-01-29-10-39

Update sync config.yaml images 2024-01-29-10-39

---

config.yaml

updates sync config.yaml images for 2024-02-01-14-09

Update sync config.yaml images 2024-02-01-14-09

---

images/rpmbuild-centos-stream8/Dockerfile
images/rpmbuild-centos-stream9/Dockerfile
images/rpmbuild-centos7/Dockerfile

node 16 EOL as of september 2023
https://nodejs.org/en/blog/announcements/nodejs16-eol

fix: update node version to supported

---

config.yaml

updates sync config.yaml images for 2024-02-09-11-30

Update sync config.yaml images 2024-02-09-11-30

---

images/rpmbuild-centos7/Dockerfile

fix: update to usable nodejs version

---

config.yaml

terraform cloud can do the work instead.

fix: remove unused terraform container

---

config.yaml

fix: update python images to latest

---

config.yaml

fix: update datadog to 7.51

---

config.yaml

updates sync config.yaml images for 2024-02-22-11-21

Update sync config.yaml images 2024-02-22-11-21

---

config.yaml

updates sync config.yaml images for 2024-02-29-16-12

Update sync config.yaml images 2024-02-29-16-12

---

config.yaml
go.mod

not sure what the go mod file does here but updated to match as well

feat: introduce go 1.21.8 security update

---

config.yaml

updates sync config.yaml images for 2024-03-06-15-50

Update sync config.yaml images 2024-03-06-15-50

---

config.yaml

updates sync config.yaml images for 2024-03-13-09-53

Update sync config.yaml images 2024-03-13-09-53

---

config.yaml

updates sync config.yaml images for 2024-03-14-13-48

Update sync config.yaml images 2024-03-14-13-48

---

config.yaml

updates sync config.yaml images for 2024-03-18-14-11

Update sync config.yaml images 2024-03-18-14-11

---

config.yaml

updates sync config.yaml images for 2024-03-27-16-47

Update sync config.yaml images 2024-03-27-16-47

---

config.yaml

updates sync config.yaml images for 2024-04-03-10-52

Update sync config.yaml images 2024-04-03-10-52

---

.github/workflows/update-image-digests.yml

geonetci has no ability to modify PR's and when run this way breaks the automation.
it would be easier to manage if it makes multiple PR's than the current solution

fix: amend digest update workflow

---

README.md
config.yaml

for local testing of puppet code and apps

feat: add alma linux

---

config.yaml

updates sync config.yaml images for 2024-04-05-15-11

Update sync config.yaml images 2024-04-05-15-11

---

config.yaml

updates sync config.yaml images for 2024-04-08-13-42

Update sync config.yaml images 2024-04-08-13-42

---

config.yaml

updates sync config.yaml images for 2024-04-10-10-32

Update sync config.yaml images 2024-04-10-10-32

---

config.yaml

updates sync config.yaml images for 2024-04-11-13-48

Update sync config.yaml images 2024-04-11-13-48

---

.github/dependabot.yml

something to make the dependabot PR's less numerous

feat: group python package updates

---

.github/dependabot.yml

fix: add hotfix for dependabot config

---

README.md
config.yaml

adding govc for vmware automations not available in terraform vsphere

feat: add vendored govc

---

config.yaml

updates sync config.yaml images for 2024-04-15-16-25

Update sync config.yaml images 2024-04-15-16-25

---

images/rpmbuild-centos7/Dockerfile

fix: node update

---

config.yaml

updates sync config.yaml images for 2024-04-16-12-57

Update sync config.yaml images 2024-04-16-12-57

---

config.yaml

updates sync config.yaml images for 2024-04-23-10-24

Update sync config.yaml images 2024-04-23-10-24

---

config.yaml

feat: add fedora 40

---

config.yaml

updates sync config.yaml images for 2024-04-24-13-12

Update sync config.yaml images 2024-04-24-13-12

---

config.yaml

updates sync config.yaml images for 2024-04-26-15-31

Update sync config.yaml images 2024-04-26-15-31

---

config.yaml

updates sync config.yaml images for 2024-04-26-16-35

Update sync config.yaml images 2024-04-26-16-35

---

config.yaml

chore: update nginx image

---

config.yaml

updates sync config.yaml images for 2024-04-29-10-12

Update sync config.yaml images 2024-04-29-10-12

---

README.md
config.yaml
images/mkdocs_material/Dockerfile
images/mkdocs_material/pyproject.toml

for replacing the legacy mkdocs_plus image

feat: add up to date mkdocs material in pyproject

---

config.yaml

updates sync config.yaml images for 2024-05-06-16-17

Update sync config.yaml images 2024-05-06-16-17

---

config.yaml

updates sync config.yaml images for 2024-05-07-14-45

Update sync config.yaml images 2024-05-07-14-45

---

README.md
config.yaml

Reference: https://github.com/GeoNet/tickets/issues/12642
Used for weekly security web scans

feat: add new OWASP ZAP proxy image

---

config.yaml

updates sync config.yaml images for 2024-05-08-09-07

Update sync config.yaml images 2024-05-08-09-07

---

config.yaml

updates sync config.yaml images for 2024-05-13-13-42

Update sync config.yaml images 2024-05-13-13-42

---

config.yaml

updates sync config.yaml images for 2024-05-21-01-39

Update sync config.yaml images 2024-05-21-01-39

---

config.yaml

updates sync config.yaml images for 2024-05-22-11-18

Update sync config.yaml images 2024-05-22-11-18

---

images/rpmbuild-centos7/Dockerfile

minor update
matching updates for el8
from https://github.com/GeoNet/base-images/pull/247

fix: update node installer link

---

README.md
config.yaml

Add new rpmbuild-almalinux8 to build list and README

chore: add rpmbuild-almalinux8 to builds

---

config.yaml

updates sync config.yaml images for 2024-05-22-15-08

Update sync config.yaml images 2024-05-22-15-08

---

config.yaml

updates sync config.yaml images for 2024-05-24-16-07

Update sync config.yaml images 2024-05-24-16-07

---

README.md
config.yaml
images/alpine-nginx-rtmp-stream/Dockerfile
images/alpine-nginx-rtmp-stream/run.sh

https://github.com/GeoNet/tickets/issues/15757
from: https://github.com/JasonRivers/Docker-nginx-rtmp

feat: add nginx rtmp for stream proxy

---

config.yaml

updates sync config.yaml images for 2024-05-24-16-18

Update sync config.yaml images 2024-05-24-16-18

---

config.yaml

updates sync config.yaml images for 2024-05-28-10-21

Update sync config.yaml images 2024-05-28-10-21

---

config.yaml

updates sync config.yaml images for 2024-06-05-16-43

Update sync config.yaml images 2024-06-05-16-43

---

config.yaml

updates sync config.yaml images for 2024-06-11-12-01

Update sync config.yaml images 2024-06-11-12-01

---

config.yaml

updates sync config.yaml images for 2024-06-12-14-03

Update sync config.yaml images 2024-06-12-14-03

---

config.yaml

updates sync config.yaml images for 2024-06-12-14-07

Update sync config.yaml images 2024-06-12-14-07

---

config.yaml
images/rpmbuild-fedora/Dockerfile
images/rpmbuild-fedora/Dockerfile.39

waiting on stream 8 pr to be merged 
https://github.com/GeoNet/base-images/pull/267

Fedora rpmbuild update

---

config.yaml

updates sync config.yaml images for 2024-06-13-14-04

Update sync config.yaml images 2024-06-13-14-04

---

config.yaml

updates sync config.yaml images for 2024-06-21-14-45

Update sync config.yaml images 2024-06-21-14-45

---

config.yaml

updates sync config.yaml images for 2024-06-24-14-06

Update sync config.yaml images 2024-06-24-14-06

---

config.yaml

updates sync config.yaml images for 2024-06-27-15-30

Update sync config.yaml images 2024-06-27-15-30

---

images/chart-centos7/Dockerfile

replaced with aws ecs golang code

chore: remove chart app

---

config.yaml

updates sync config.yaml images for 2024-06-27-19-23

Update sync config.yaml images 2024-06-27-19-23

---

config.yaml

remove from config yaml centos7-chart app

fix: remove chart config

---

config.yaml

updates sync config.yaml images for 2024-07-01-15-50

Update sync config.yaml images 2024-07-01-15-50

---

README.md
config.yaml

vendor the official prometheus container image

feat: add prometheus container

---

config.yaml

updates sync config.yaml images for 2024-07-02-10-36

Update sync config.yaml images 2024-07-02-10-36

---

config.yaml

updates sync config.yaml images for 2024-07-04-09-59

Update sync config.yaml images 2024-07-04-09-59

---

config.yaml

Update golang from 1.21.8 to 1.21.12

fix: update golang image in config.yaml

---

config.yaml

updates sync config.yaml images for 2024-07-04-10-15

Update sync config.yaml images 2024-07-04-10-15

---

config.yaml

updates sync config.yaml images for 2024-07-08-11-48

Update sync config.yaml images 2024-07-08-11-48

---

config.yaml

updates sync config.yaml images for 2024-07-23-12-12

Update sync config.yaml images 2024-07-23-12-12

---

images/rpmbuild-almalinux8/Dockerfile
images/rpmbuild-centos-stream9/Dockerfile

stop downloading on package builds from mirrors

fix: add python3.11 to el8 & el9

---

config.yaml

updates sync config.yaml images for 2024-08-06-08-39

Update sync config.yaml images 2024-08-06-08-39

---

.github/workflows/update-image-digests.yml
config.yaml

updates sync config.yaml images for 2024-08-07-17-04

Update sync config.yaml images 2024-08-07-17-04

---

README.md
sync-ghcr.yml

Vendor images for snmp-exporter and blackbox-exporter.

feat: add prometheus snmp and blackbox exporters

---

sync-ghcr.yml

fix: add hotfix for skopeo tag

---

.github/workflows/sync.yml

I left it under my test namespace, sorry.

fix: set namespace back to geonet

---

.github/workflows/sync.yml

add token from github actions to address 
sync script not working and retuning 403

fix: add change for token 403 failure

---

sync-ghcr.yml

for use in https://github.com/GeoNet/base-machine-images

feat: add packer container for CI use

---

sync-ghcr.yml

every minor release and associated sha was taking too long to sync

fix: reduce number of alpine images to sync

---

.github/workflows/sync.yml

- preserve digests
- only retry once (saving limited number of dockerhub api requests)

fix: stop printing debug messages

---

sync-ghcr.yml

major version for alpine almalinux and fedora

feat: add new version for development

---

.github/workflows/sync.yml

feat: update skopeo version

---

README.md
sync-ghcr.yml

Vendor the hashicorp terraform cloud agent image

feat: add tfcloud agent

---

sync-ghcr.yml

With alpine 3.21 which came out recently

feat: add Go 1.23 image

---

.github/workflows/build-magpi.yml
images/rpmbuild-fedora/Dockerfile

Add github actions workflow for running arm fedora codebuild builds.

feat: add gha for codebuild fedora arm

---

sync-ghcr.yml

Dumb, used ringsever instead of ringserver

fix: update spelling of ringserver

---

sync-ghcr.yml

feat: add node v22 image

---

config.yaml
images/ubuntu-pdk/Dockerfile

for more reliable local testing on any OS

feat: add stable pdk to match gh actions

---

sync-ghcr.yml

fix: incorrect minor version for golang:alpine

---

.github/workflows/sync.yml

to resolve issues publishing prometheus and other semver based images

fix: reverse auth to use geonetci auth

---

.github/workflows/sync.yml

fix: clarify sync.yml messages

---

sync-ghcr.yml

feat: add centos stream10

---

images/python-arcgis/Dockerfile
images/python-arcgis/pyproject.toml

Tested with `ArcGIS_Publish` integration test, works.

Switch to bullseye, update poetry,arcgis, and pandas for python-arcgis image.

---

sync-ghcr.yml

This adds the victoria metrics single node option from docker

feat: add victoria metrics image

---

config.yaml
images/rpmbuild-centos-stream10/Dockerfile
images/rpmbuild-centos-stream10/rpmlintrc.toml

feat: add first run at centos10 rpmbuild

---

sync-ghcr.yml

This is in the victoria metrics family, and relates to self help with logging

feat: add victoria-logs image

---

sync-ghcr.yml

Reference: https://github.com/GeoNet/tickets/issues/18639

feat: add new image for owasp zaproxy webscan

---

sync-ghcr.yml

feat: add debian trixie
