config.yaml
changes include
- add ubi8, along side ubi8-minimal
- update debian:bullseye to debian:bookworm
- update python images
- update Terraform images
- use node alpine instead of node debian
=> chore: update images

README.md, config.yaml, images/chart-centos7/Dockerfile
This is required as a stop gap until some legacy code can be upgraded or coded around.
=> feat(chart): add a specific centos7 base image for chart

README.md, config.yaml
Reference: https://github.com/GeoNet/devx/issues/136
Note: no idea what I'm doing.
I want to add [this OWASP docker image](https://hub.docker.com/layers/owasp/zap2docker-stable/2.11.1/images/sha256-47911f0e0fc82ab2e660bc2af54c84bae0f4b7b1f89f25b0a7d6e5baa163594a) we use for the [weekly security webscan](https://github.com/GeoNet/DevTools/blob/069444594014ca8a9fc1e4dc48bf0bb2234f236b/cmd/webscan/Dockerfile#L19) in `DevTools` (used to be in `devx`, hence the devx ticket).
Let me know if there's anything else I need to do.
=> Add OWASP zap scan image

.github/workflows/images-are-public.yml
runs on main for after image have been built and synced
=> feat: add workflow to verify images are public

README.md, config.yaml
fedora is the preferred OS for edge compute.
It is rpm based and supports new hardware like the arm64 raspberry pi well.
These images are vendored for github actions usage.
Related ticket https://github.com/GeoNet/tickets/issues/12984
=> add fedora images

config.yaml
=> chore: update fedora-coreos image for 20230726

config.yaml
it was outta date
failing here
https://github.com/GeoNet/base-images/actions/runs/5779676025/job/15665244128
=> chore: update fedora image digest

images/alpine-gdal/image.yaml, images/alpine-xslt/image.yaml, images/git/image.yaml
removes shell entrypoint for images which don't ship shells
=> fix: remove entrypoints from shell-less images

config.yaml
attempt to resolve requirement for apk in some image builds
issue: https://github.com/GeoNet/4D-Ashfall/actions/runs/5898532654/job/15999708341?pr=35#step:19:197
cc @CallumNZ 
although, the Chainguard images are preferred since they can be reproducibly built, they don't ship with package managers
=> chore: use standard golang images

config.yaml
=> chore: update centos and fedora-coreos images

README.md, config.yaml
adds a copy of the shellcheck container
depends on: https://github.com/GeoNet/Actions/pull/174
=> feat: add shellcheck to sync

.github/workflows/build.yml, .github/workflows/scan.yml, .github/workflows/sync.yml
on fail, don't cancel other jobs
=> chore: try to not cancel separate matrix jobs

config.yaml
=> chore: update Go 1.20 and Go 1.21 images

config.yaml
=> chore: bump centos and fedora coreos images

README.md, config.yaml, images/rpmbuild-centos-stream8/Dockerfile, images/rpmbuild-centos-stream9/Dockerfile, images/rpmbuild-centos7/Dockerfile
adds the following rpmbuild images
- CentOS 7
- CentOS Stream 8
- CentOS Stream 9
=> feat: add rpmbuild base images for packaging

config.yaml
use multi-arch image to support local builds
=> chore: update go 1.21.1 image

.github/workflows/presubmit-signed-images-are-signed.yml, .github/workflows/sync.yml, config.yaml
verify signatures for signed images for syncing images
=> feat: add verify check to signed container images

.github/workflows/sync.yml, README.md, config.yaml
vendors the datadog agent image to an ECR
adds AWS and ECR auth to sync function (not build).
Requires an ECR for _datadog-agent_ to exist.
depends on: https://github.com/GeoNet/terraform-aws/pull/938
fixes: https://github.com/GeoNet/tickets/issues/10235
=> feat: sync datadog agent to ECR

.github/workflows/images-are-public.yml
ecr is for private image artifacts
=> chore: filter out ecr from public check

config.yaml, images/alpine-gdal/image.yaml
I assume currently the only project using this container is Shakinglayer, which's code only works with Gdal 3.4.
And, the Shakinglayer's base build image is Go1.16, which gives Gdal 3.4, and the existing GeoNet/alpine-gdal uses Alpine 3.18, give Gdal 3.6. This causes the runtime error.
Unfortunately we need to downgrade to Alpine 3.15 to get Gdal 3.4 so builder and runner can be in sync.
Also the code only works when it's Gdal 3.4.
Built instances deployed in dev environment works well.
=> fix: Downgrade GeoNet/alpine-gdal to Alpine 3.15

config.yaml
The scheduled update job failed due to the hashes not existing.
Looking at the history, I can see these were changed https://quay.io/repository/centos/centos?tab=history
=> chore: update centos stream hashes

.github/workflows/build.yml
newer version requires update to the forked/vendored action in our org namespace
prints:
Status: Downloaded newer image for ghcr.io/wolfi-dev/apko:latest Error: unknown flag: --package-version-tag-stem
2023/11/03 00:05:35 error during command execution: unknown flag: --package-version-tag-stem
=> fix: pin version of chainguard to last working version

config.yaml
sync from quay.io the arm64 image
primarily for containerised compute at edge builds
=> fix: force arm64 on fedora

images/rpmbuild-centos-stream8/Dockerfile, images/rpmbuild-centos-stream9/Dockerfile, images/rpmbuild-centos7/Dockerfile, images/rpmbuild-fedora/Dockerfile
in order to sync from s3 during each package build these containers need aws cli
=> feat: add aws cli v2 for rpmbuilds

config.yaml
busywork as centos:7 tag is now missing :-1:
=> fix: centos upstream image tag

images/rpmbuild-centos7/Dockerfile
Enable for EL7 so we can use rpm signing in GitHub Actions builds
=> fix: add openssl11 for rpm signing to EL7 jobs

config.yaml
updates sync config.yaml images for 2024-01-11-13-28
=> Update sync config.yaml images 2024-01-11-13-28

images/rpmbuild-centos7/Dockerfile
mistakenly using arm download for x86_64 target
=> fix: correct c7 node version install

config.yaml, images/alpine-gdal/image.yaml
Previously we downgrade alpine 1.18 to 1.15 for gdal, now in order to use Go 1.21 for services, we're upgrading back to alpine 1.18.
Two extra drivers have been spun off to standalong packages, adding them by apk.
=> chore: upgrade to alpine-gdal:1.18

.github/workflows/update-image-digests.yml
this check suite should run when the geonetci bot syncs from quay.io for mutable tags
checks	Work with check runs and check suites. For example, checks: write permits an action to create a check run. For more information, see "Permissions required for GitHub Apps."
=> fix: try to run the check suite on upstream sync

config.yaml
For ArcGIS project, needs Python 3.11 and a version of Rust not available in alpine 3.18.
=> feat: add image for python 3.11 for alpine 3.19

README.md, config.yaml, images/python-arcgis/Dockerfile, images/python-arcgis/pyproject.toml
Reference: https://github.com/GeoNet/tickets/issues/15495
arcgis takes a long time to install which was hitting our Github Action limit when doing docker build. I've also added some other python packages that are commonly used with arcgis, like pandas and numpy.
=> feat: add base image containing python arcgis

.github/workflows/update-image-digests.yml
will only succeed on first push
created to address issues found in https://github.com/GeoNet/base-images/pull/220
=> feat: assign reviewer on creation

config.yaml
going back to drawingboard with dev team 
https://github.com/GeoNet/tickets/issues/12642
=> fix: remove owasp image

images/rpmbuild-almalinux8/Dockerfile
CentOS Stream8 will be EOL soon, so this adds alternative for rpm builds
=> chore: add almalinux8 rpm builds

images/rpmbuild-almalinux8/Dockerfile
=> fix: remove alma python 3.6

README.md, config.yaml
Reference: https://github.com/GeoNet/tickets/issues/16099
Required for volcano dashboard project.
`11.1.0` is the latest version. 
It is based on Alpine.
=> feat: add Grafana image

config.yaml
updates sync config.yaml images for 2024-08-22-12-11 from fedora
=> fix: update sync config.yaml images for 2024-08-22-12-11

config.yaml
Remove CentOS7 rpmbuild image we no longer need
=> nfc: remove centos7 rpmbuild image

.github/workflows/sync.yml, sync-ghcr.yml
dry run doesn't catch the missing upstream
run sync even if the upstream is missing on one entry so most things get updates
removing broken chainguard image that is unused ghcr.io/geonet/base-images/node:20
=> fix: allow sync to finish before failing

.github/dependabot.yml
currently the dependabot configuration is not useful to us the dependabot system is blocked on merging unhelpful PR's for mkdocs
mkdocs will be addressed in this ticket instead https://github.com/GeoNet/tickets/issues/15171
this change scopes python updates to a component service of a data product (arcgis online uploader base image)
hopefully this means we get automation for image updates from the new image sync tooling
=> feat: change scope of dependabot checks

sync-ghcr.yml
github uses an old version of skopeo and we need an updated one for semver support
=> fix: add skopeo to vendored software

.github/workflows/sync.yml
to use up to date skopeo from our vendored copy
requires https://github.com/GeoNet/base-images/pull/312
=> feat: add podman runtime for sync

.github/workflows/sync.yml
resolves issues with 403 messages saving to ghcr.io 
adds our token to sync from dockerhub
this may still fail due to the number of images we need to sync to catch up to latest
=> fix: add authentication to the skopeo container running under podman

.github/workflows/sync.yml
this was supposed to allow dry-run vs run on main but got this error 
`Error: authenticating creds for true: pinging container registry true: Get https://true/v2/: dial tcp: lookup true: Temporary failure in name resolution`
my mistake
=> fix: change ecr env var to avoid clash

images/python-arcgis/Dockerfile, images/python-arcgis/pyproject.toml
Updated `numpy`, `pandas`, and `geopandas`.
Ran integration test with downstream application, works fine.
=> Arcgis dependency updates

sync-ghcr.yml
20.3-alpine3.18 is what we're currently using across the board. 21.6-alpine3.19 is the new image we want to move to.
=> fix: add alpine node images to ghcr

sync-ghcr.yml
A preparation for next update.
Also this fixes a CVE https://pkg.go.dev/vuln/GO-2024-3106
=> feat: Go 1.22 base image

sync-ghcr.yml
the format is different depending if you go for `almalinux/version-number` or `almalinux:version-number`
=> fix: change almalinux tags to match dockerhub

.github/workflows/build-magpi.yml
The existing tag conflicts with the x86 one.
I also didn't see why we needed build and tag as separate steps so I've just deleted the tag step and built with the correct tag.
=> fix: rename arm64 rpmbuild image to new tag

sync-ghcr.yml
This updates the synching to include earthscope/ringerver to present a local copy. Only the 4.0.0 image is configured
=> feat: add ringserver image

sync-ghcr.yml
This origin 4.0.0 should have been v4.0.0, updating at the same time. This is tag on the main github branch, but doesn't seem to have been turned into a release
=> feat: bump ringserver to v4.0.1

.github/workflows/sync.yml, sync-ghcr-all.yml, sync-ghcr.yml
arm images can be published under the same tag as an amd64 image.
in that instance the client OS+arch is assumed to be the desired target.
we need to override this to sync arm64 images to our repository for downstream consumption.
=> feat: add arm64 support for arbitrary images when they are composite manifests

sync-ghcr.yml
fix: add images for go1.23.6 to fix Vulnerability: [GO-2025-3447](https://pkg.go.dev/vuln/GO-2025-3447)
=> fix: add images for go1.23.6

sync-ghcr.yml
Having the minor version pinned is not practical in most cases. When there's a new govuln alert, all CIs fail and require PRs to update the dockerfiles to a new image in over 30 repos.
EDIT.
After talking about it in standup, maybe we should just stick to minor version.... 😭 I don't know what to do.
I didn't know about the scenario last year where the latest version had the vulnerability, but earlier versions didn't.
=> fix: add image for go 1.23 without minor version

images/rpmbuild-almalinux8/Dockerfile, images/rpmbuild-centos-stream9/Dockerfile
To avoid the need to install during the build steps in GitHub CI
=> fix: add python3.11-rpm-macros to rpmbuild image

images/rpmbuild-almalinux8/Dockerfile
We should drop the Almalinux 8.9 image
=> feat: update rpmbuild to almalinux 8.10

images/dell-emc-cli/Containerfile
From previous work updating dell storage certs.
Tracking this Containerfile entry so we don't lose it. If we need to build this image in future we'll need to update the package name.
=> feat: add unity-cli image for dell emc management

images/almalinux-gsm/Dockerfile, images/almalinux-gsm/gsm.exp
Provide an image to make it easy to run gsm to inspect package updates and file layout changes, especially for shared libraries
Defaults to not providing user authentication.
Can be built and run locally:
`podman build --tag almalinux-gsm .`
`podman run --rm -it localhost/almalinux-gsm:latest`
`./gsm info`
=> feat: add almalinux-gsm image for looking at gempa packages

images/dell-emc-cli/Containerfile, sync-ghcr.yml
Quick clean-up of AlmaLinux use in base-images
The dell-emc image is not intended to be a regular build which is why it's not named `Dockerfile` for the docker build workflow
=> Drop Almalinux 8.9 and use AlmaLinux 8.10

.github/workflows/sync.yml, README.md, sync-ecr.yml
- not required anymore since `datadog-agent` in ecs are now pointing to official datadog ecr repo
- this also resolves the error on the sync workflow https://github.com/GeoNet/base-images/actions/runs/14375443388
=> nfc: remove ecr sync for datadog agent

sync-ghcr.yml
Going to switch to debian for arcgis-python image
=> feat: add image for python 3.11.9-bullseye

README.md, sync-ghcr.yml
This is part of the victoria metrics system, it can be used to monitor the system itself or as an alternative to prometheus
=> feat: add vmagent image
